services:
  app:
    container_name: fleetctrl-hub
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
      args:
        CONVEX_SITE_URL: ${CONVEX_SITE_URL}
        NEXT_PUBLIC_CONVEX_SITE_URL: ${NEXT_PUBLIC_CONVEX_SITE_URL}
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT:-3000}:3000"
    env_file:
      - ./.env
